#!/usr/bin/env python3
"""Generate include/config_generated.h and firmware/common/config_defaults.c from merged YAML profiles."""

from __future__ import annotations

import argparse
import copy
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("PyYAML required: pip install pyyaml", file=sys.stderr)
    sys.exit(1)


def deep_merge(base: dict, overlay: dict) -> dict:
    result = copy.deepcopy(base)
    for key, value in overlay.items():
        if key in result and isinstance(result[key], dict) and isinstance(value, dict):
            result[key] = deep_merge(result[key], value)
        else:
            result[key] = copy.deepcopy(value)
    return result


def load_yaml(path: Path) -> dict:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    return data if isinstance(data, dict) else {}


def flatten(d: dict, prefix: str = "") -> list[tuple[str, object]]:
    out: list[tuple[str, object]] = []
    for k, v in d.items():
        key = f"{prefix}.{k}" if prefix else k
        if isinstance(v, dict):
            out.extend(flatten(v, key))
        else:
            out.append((key, v))
    return out


def c_name(path: str) -> str:
    return "CFG_" + path.upper().replace(".", "_").replace("-", "_")


def c_float(v: object) -> str:
    if v is None:
        return "0.0f"
    if isinstance(v, bool):
        return "1.0f" if v else "0.0f"
    if isinstance(v, int):
        return f"{float(v)}f"
    return f"{float(v)}f"


def emit_header(flat: list[tuple[str, object]], out: Path) -> None:
    lines = [
        "/* Auto-generated by tools/gen_config.py — do not edit */",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
    ]
    for path, val in flat:
        name = c_name(path)
        if isinstance(val, str):
            escaped = val.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'#define {name} "{escaped}"')
        elif isinstance(val, bool):
            lines.append(f"#define {name} ({'1' if val else '0'})")
        elif isinstance(val, int) and not isinstance(val, bool):
            if "addr" in path.lower():
                lines.append(f"#define {name} (0x{val:X}U)" if val > 255 else f"#define {name} ({val})")
            else:
                lines.append(f"#define {name} ({val})")
        elif isinstance(val, float) or (isinstance(val, int) and "hz" in path.lower()):
            lines.append(f"#define {name} ({c_float(val)})")
        elif val is None:
            lines.append(f"#define {name}_IS_NULL 1")
            lines.append(f"#define {name} (0)")
        else:
            lines.append(f"#define {name} ({val})")
    lines += [
        "",
        "typedef struct {",
        "    float rated_voltage_v;",
        "    uint8_t pole_pairs;",
        "    float phase_resistance_ohm;",
        "    float phase_inductance_mh;",
        "    float rated_current_a;",
        "    float max_current_a;",
        "    float gearbox_ratio;",
        "    uint32_t encoder_counts_per_rev;",
        "    uint32_t ssi_clock_hz;",
        "    int32_t encoder_electrical_offset;",
        "    float foc_pwm_hz;",
        "    float foc_loop_hz;",
        "    float speed_loop_hz;",
        "    float position_loop_hz;",
        "    uint8_t can_node_id;",
        "    uint32_t can_bitrate_kbps;",
        "    int32_t joint_zero_offset;",
        "    int32_t joint_min_position;",
        "    int32_t joint_max_position;",
        "    uint16_t joint_max_torque_pct;",
        "    uint8_t sensorless_enabled;",
        "    uint8_t sensorless_fallback_on_enc_fault;",
        "} app_config_t;",
        "",
        "extern const app_config_t g_config_defaults;",
        "void config_apply_defaults(app_config_t *cfg);",
        "",
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "",
    ]
    out.write_text("\n".join(lines), encoding="utf-8")


def emit_defaults(data: dict, out: Path) -> None:
    jx = data.get("joint_axis", {})
    body = f"""/* Auto-generated by tools/gen_config.py — do not edit */
#include "config_generated.h"
#include <string.h>

const app_config_t g_config_defaults = {{
    .rated_voltage_v = {data['motor']['rated_voltage_v']}f,
    .pole_pairs = {data['motor']['pole_pairs']},
    .phase_resistance_ohm = {data['motor']['phase_resistance_ohm']}f,
    .phase_inductance_mh = {data['motor']['phase_inductance_mh']}f,
    .rated_current_a = {data['motor']['rated_current_a']}f,
    .max_current_a = {data['motor']['max_current_a']}f,
    .gearbox_ratio = {data['gearbox']['ratio']}f,
    .encoder_counts_per_rev = {data['encoder']['counts_per_rev']},
    .ssi_clock_hz = {data['encoder']['ssi_clock_hz']},
    .encoder_electrical_offset = {data['encoder']['electrical_offset_counts']},
    .foc_pwm_hz = {data['foc']['pwm_frequency_hz']}f,
    .foc_loop_hz = {data['foc']['control_loop_hz']}f,
    .speed_loop_hz = {data['speed_loop']['rate_hz']}f,
    .position_loop_hz = {data['position_loop']['rate_hz']}f,
    .can_node_id = {data['can']['node_id']},
    .can_bitrate_kbps = {data['can']['bitrate_kbps']},
    .joint_zero_offset = {jx.get('zero_offset_counts', 0)},
    .joint_min_position = {jx.get('min_position_counts') or 0},
    .joint_max_position = {jx.get('max_position_counts') or 0},
    .joint_max_torque_pct = {jx.get('max_torque_pct', 1000)},
    .sensorless_enabled = {1 if data.get('sensorless', {}).get('enabled') else 0},
    .sensorless_fallback_on_enc_fault = {1 if data.get('sensorless', {}).get('fallback_on_enc_fault', True) else 0},
}};

void config_apply_defaults(app_config_t *cfg)
{{
    if (cfg != NULL) {{
        memcpy(cfg, &g_config_defaults, sizeof(g_config_defaults));
    }}
}}
"""
    out.write_text(body, encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--platform", default="config/platform.yaml")
    ap.add_argument("--board", default="boards/hy_gb4212_drv_a4/board.yaml")
    ap.add_argument("--motor", default="config/motors/gb4212_18v.yaml")
    ap.add_argument("--application", default="", help="Optional application overlay YAML")
    ap.add_argument("--header", default="include/config_generated.h")
    ap.add_argument("--source", default="firmware/common/config_defaults.c")
    args = ap.parse_args()

    root = Path(__file__).resolve().parents[1]
    paths = [
        root / args.platform,
        root / args.board,
        root / args.motor,
    ]
    if args.application:
        paths.append(root / args.application)

    data: dict = {}
    for p in paths:
        if not p.exists():
            print(f"Missing config: {p}", file=sys.stderr)
            return 1
        data = deep_merge(data, load_yaml(p))

    for required in (
        "motor",
        "gearbox",
        "encoder",
        "foc",
        "speed_loop",
        "position_loop",
        "can",
        "ota",
        "startup_protection",
        "probe",
    ):
        if required not in data:
            print(f"Merged config missing required section: {required}", file=sys.stderr)
            return 1

    hdr = root / args.header
    src = root / args.source
    flat = flatten(data)
    hdr.parent.mkdir(parents=True, exist_ok=True)
    src.parent.mkdir(parents=True, exist_ok=True)
    emit_header(flat, hdr)
    emit_defaults(data, src)
    print(f"Generated {hdr} and {src} from:")
    for p in paths:
        print(f"  - {p.relative_to(root)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
